version: '2'
services:
  elasticsearch:
    image: arcseldon/elasticsearch-kibana-marvel-sense
    mem_limit: 1500m
    ports:
      - "9200:9200"
      - "9300:9300"
      - "5601:5601"
  kafka:
    image: wurstmeister/kafka:0.10.0.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zk:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock